#!/bin/bash
set -euo pipefail

# usage() {
#   echo "Usage: $0 RESOURCE_TYPE ::= <node-name> | <pod-name> NAMESPACE ::= <namespace-name>"
# }
# if [[ ( $* == "--help") ||  $* == "-h" ]]; then
#   usage
# 	exit 0
# fi 

RESOURCE_TYPE="${1:-pod}"
NAMESPACE="${2:-default}"

# Retrieve resource usage statistics from Kubernetes
NAME=
CPU=
MEMORY=
printf  "%-8s | %-10s | %-15s | %-7s | %-7s\n" "Resource" "Namespace" "Name" "CPU" "Memory"
while read -r line
do
  # Extract CPU and memory usage from the output
  NAME=$(echo "${line}" | awk '{print $1}')
  CPU=$(echo "${line}" | awk '{print $2}')
  MEMORY=$(echo "${line}" | awk '{print $3}')

  # Output the statistics to the console
  printf "%-8s | %-10s | %-15s | %-7s | %-7s\n" "$RESOURCE_TYPE" "$NAMESPACE" "$NAME" "$CPU" "$MEMORY"
done < <(kubectl top "${RESOURCE_TYPE}" -n "${NAMESPACE}" | tail -n +2)
